GROUP=io.galva.sdk
VERSION_NAME=1.1.0-SNAPSHOT
JS_BRIDGE_VERSION="1.0.0"

POM_NAME=Galva Android SDK
POM_DESCRIPTION=Pure Kotlin core for the Galva SDK
POM_URL=https://github.com/Galva-io/galva-android
POM_INCEPTION_YEAR=2026

POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/Galva-io/galva-android
POM_SCM_CONNECTION=scm:git:git://github.com/Galva-io/galva-android.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/galva-android.git

POM_DEVELOPER_ID=linhttbk97
POM_DEVELOPER_NAME=LinhTT
POM_DEVELOPER_EMAIL=tailinh@unstatic.co

BASE_API_URL="https://api.galva.dev"
BASE_API_URL_PROD="https://api.revflow.dev"
BASE_WEBVIEW_IAM_URL="https://webview.galva.dev/"
BASE_WEBVIEW_IAM_URL_PROD="https://webview.revflow.dev/"

org.gradle.parallel=true
org.gradle.caching=true

mavenCentralUsername=26FoAI
mavenCentralPassword=gB89bFKZm6B9SwkQg45oIBLfUPBtdUyNv
signingInMemoryKeyId=CED2E8CE
signingInMemoryKeyPassword=Unstatic2026@
signingInMemoryKey=lIYEahazvhYJKwYBBAHaRw8BAQdA8TSSFxxP8po7CO1xLhJeSZEY5gP/8mQP4eSQYe6VS+X+BwMCBhd3Y1RKdFr++sM/eLRoUOIWggT7+emDkqa/aW9UkRqssq6WWHYWYq26EL19JZht/S+oPupWmuo9yK7c6DftvQUCUJgm+UTSK8HfBmpvm7QddGFpbGluaCA8dGFpbGluaEB1bnN0YXRpYy5jbz6ItQQTFgoAXRYhBAh9Yswxl7j4uzk3T6Z4MFuoYvxoBQJqFrO+GxSAAAAAAAQADm1hbnUyLDIuNSsxLjEyLDIsMQIbAwUJBaOagAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRCmeDBbqGL8aEUlAQClHMBDN50I83URWYnCuHEA090FocPXCCHG9ouM/P9MPAD/UUilXp5zti58RiYo1Ag3wpVfk7rF61cs9YwhDLBvOACciwRqFrO+EgorBgEEAZdVAQUBAQdAMKyeNU3k8Ozs+KrV3q/oyYvqIW3KaxdF6zor258ZyjwDAQgH/gcDAtrMEv2aPy0s/mVJrt/P0lPXj2C5eMoXgwNClgtTFs1BJZlpZ8pTOYwDZ8Grh318a7UBxXTAbane97/kIPp5SC5s/Uh2y/mlbkuXOBazw/KImgQYFgoAQhYhBAh9Yswxl7j4uzk3T6Z4MFuoYvxoBQJqFrO+GxSAAAAAAAQADm1hbnUyLDIuNSsxLjEyLDIsMQIbDAUJBaOagAAKCRCmeDBbqGL8aF2vAQC7yre+teUG0mnMYUnzPcBQlmuEELtdGVhK5Uhq0Dj0xgEAl5NrkTozfR2Y0W3OVWeC+GDEY5n6KLnrXeOjrVHgmws=


