[versions]
agp = "9.0.0"
kotlin = "1.9.0"
vanniktech = "0.36.0"

appcompat = "1.7.1"
material = "1.13.0"
coreKtx = "1.18.0"

junit = "4.13.2"
kotlinxCoroutines = "1.11.0"
kover = "0.9.8"
robolectric = "4.16.1"
coreKtxVersion = "1.7.0"
datastore = "1.2.1"
okhttp3 = "5.3.2"
androidDesugarJdkLibs = "2.1.5"
lifecycle = "2.9.4"
serialization = "1.6.0"
webkit = "1.16.0"
billing = "8.0.0"
mockito = "6.3.0"
androidxActivity = "1.8.0"

[libraries]

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version = "lifecycle" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kover-gradlePlugin = {group= "org.jetbrains.kotlinx" ,name = "kover-gradle-plugin", version.ref = "kover"}
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
mockwebserver = {group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp3"}
maven-publish-gradle = {group="com.vanniktech", name="gradle-maven-publish-plugin",version.ref="vanniktech"}
billing-ktx = {group = "com.android.billingclient", name = "billing-ktx", version.ref = "billing"}
mockito-kotlin = {group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito"}

junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-test ={ group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
robolectric = {group = "org.robolectric", name = "robolectric", version.ref ="robolectric"}
turbine = {group = "app.cash.turbine",name ="turbine",version = "1.1.0"}
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }

[plugins]
android-application = {id = "com.android.application" ,version.ref = "agp"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover"}
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
vanniktech-maven-publish = {id = "com.vanniktech.maven.publish",version.ref = "vanniktech"}

# galva sdk convention plugins
galva-android-application = {id = "io.galva.android.sdk.application"}
galva-android-library = {id = "io.galva.android.sdk.library"}
galva-android-test= {id = "io.galva.android.sdk.test"}
galva-serialization= {id = "io.galva.android.sdk.serialization"}
galva-publishing = {id = "io.galva.android.sdk.publishing"}